### ISSUE TITLE
Openness in legislation, we can include the licence as indicator?

### ISSUE THREAD

**Issue by ppKrauss** [okfn/opendatacensus#555]
The openness of a country's legislation (a set of law-documents) can be expressed by the *license* of the documents, so, it is a good criterium for Open Data Census...  But, except of [UK legislation](http://www.legislation.gov.uk/browse) where each law-document have an explicit license ([OGL](https://en.wikipedia.org/wiki/Open_Government_Licence)), most countries not offer explicit or implicit license. The "license" of the law-documents must be inferred.

Even "inferred license" is a good indicator. 

Another interesting aspect on the *openness of legislation*, indicated by its license,  is the necessary (for preserve citizen rights) ["citation-alike observance" described here](https://github.com/okfn/opendefinition/wiki/Citation-alike-clauses-of-open-licenses-for-law#user-content-the-citation-alike-clause-and-observance). When we checked this observance, it offers a measure of the coherence of the legal system about its openness compromises.

**Comment by pwalsh** [comment]
@morchickit

**Comment by morchickit** [comment]
Well, from the Israeli case, apparently even a law didn't prevent government officials to take civil society to court about bills copyrights (which, by Israeli law are creative commons)... so I inclined to keep the license, unless it's a unique case like Iceland. 
@rgrp - your thoughts?

**Comment by ppKrauss** [comment]
@morchickit thanks! Allow me to explain further, I edited the question and added links, now perhaps more readable avoiding mistakes... Sorry I haven't done it before.

About Israeli law-documents, are [CC-BY](https://creativecommons.org/licenses/by/3.0/),   [CC0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) or another creative commons?

The  PDF [law-documents of UK](http://www.legislation.gov.uk/browse) have explicit "© Crown copyright", and HTML version are automatically licensed by [OGL](https://en.wikipedia.org/wiki/Open_Government_Licence), that is a kind of [CC-BY](https://creativecommons.org/licenses/by/3.0/).  I checked Iceland and many others... There are no © (at PDFs) or specific licenses.

And about Israeli law-document citating an external document? When a law need  to cite, ex. an copyrighted technical norm (ex. [ISO](http://www.iso.org/iso/store.htm)), what the Israeli legislator do? (ex.  cite and lets citizen to pay to read ISO). 
PS: in Brasil, after decades, the technical body, ABNT, was [enforced](http://www.pessoacomdeficiencia.gov.br/app/normas-da-abnt/termo-de-ajustamento-de-conduta) to  [offer open access to 48 technical norms cited-by-law ](http://www.secovi.com.br/noticias/acesse-gratuitamente-as-normas-tecnicas-da-abnt/7346/), that was before copyrighted.

**Comment by morchickit** [comment]
So, in Israel, the law is equivalent to CC-BY, BUT the website never states it. So, the legal department of the parliament see it as free license when it is actually not stating it anywhere in the website. 
@tryggvib - can you elaborate about the Iceland case?

**Comment by tryggvib** [comment]
The Icelandic "Information law" of 2012 has an article (article 30) on reuse of public sector information, here it is translated by me:

> "Article 30. Generic terms for reuse of public sector information.
> It is allowed to reuse public sector information which has been made accessible to the general public according to law, as long as the these conditions are followed:
>    1. Reuse of the information cannot violate other laws, including criminal law, copyright law and law about privacy laws, nor the rights of a third party.
>    2. Source of the information shall be attributed.
>    3. It shall be clear who is responsible for processing the information when it is made accessible to others."

These are the general terms in Iceland for all public sector information that has been made available. Of these I have discussed the explicit mention of *copyright law* in the first item of the list which in my opinion can cause confusion, but lawyers I've discussed this with say that these terms apply to both the public entity as well as the user and that the first item is supposedly aimed at the public entities who should not violate copyright when they make their own information available. I don't really see how they can do that which is why I'm more inclined to interpret this as being aimed at the general public.

Anyways, there has been a discussion that I've participated in which was supposed to lead to an open license in Iceland, similar to the one in the UK (OGL). Lawyers at the prime minister's office who would publish such a license have claimed that it is unneeded because the general terms are already in the information laws. No license can ever override "generic terms" and the generic terms are so broad that a license will either restrict the terms (which the executive branch of government cannot do) or just say the same thing. So the conclusion from the government side is that there cannot be a government license, only guidelines that help the general public **and** public entities to follow the law (i.e. say the same thing as the laws).

That's the gist of it. @morchickit any more elaboration you need?

**Comment by ppKrauss** [comment]
Hi, thanks for all, I will reply (!)... But I need some time to work with a "discussion consolidation" at https://github.com/ppKrauss/openCoherence

Here an [example of consolidated discussion about "Brazilian inferred license"](https://github.com/ppKrauss/openCoherence/blob/master/reports/inferredLicense-BR.md)... I thing other can follow this model and [this template](https://github.com/ppKrauss/openCoherence/blob/master/reports/template.md).

**Comment by pwalsh** [comment]
@morchickit should this conversation move to the forum?

**Comment by ppKrauss** [comment]
@morchickit , I only need a little "free time" (the next weekend) to build  some concrete experiments, them back here with better fundamentals...  

I am preparing   a draft for [Inferred license for Israeli legislation](https://github.com/ppKrauss/openCoherence/blob/master/reports/inferredLicense-IL.md), can you check?

**Comment by ppKrauss** [comment]
Ops, sorry, my answer was for @pwalsh

**Comment by pwalsh** [comment]
Hi @ppKrauss it is no problem, I'm in no rush or anything, it is just that we are trying to keep discussion of methodology on the [discussion forum](https://discuss.okfn.org/c/open-data-index), and use GitHub here for technical issues. 

At the same time, it is perfectly fine to discuss here, you just might get less input from other people interested in these issues (as these people frequent the forum).

**Comment by morchickit** [comment]
I'm with @pwalsh - let's move it to the forum, we will have much more input from others there.
