### ISSUE TITLE
http://australia.census.okfn.org/admin returns {"status":"error","message":"not allowed"}

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#578]
Clues?

**Comment by pwalsh** [comment]
not logged in.

**Comment by Stephen-Gates** [comment]
Nope. Was logged in. 
Logged out and logged back in and same error.

Interestingly it shows my logged in name as Stephen but submission (on Au_City) shows name as Stephen Gates - Intended?

**Comment by pwalsh** [comment]
@Stephen-Gates your admin email for the census is your @me.com email address. In the new code, that email needs to match the email of your logged in user in order to allow access to the admin controls of the census. I had this restriction relaxed on the test **next** site. I believe this is the issue here. Please email me directly and let me know which email I should use for your admin email.

**Comment by Stephen-Gates** [comment]
@pwalsh email sent

**Comment by pwalsh** [comment]
I'm closing this as it is a configuration issue in the site registry, and I am sorting it out with @Stephen-Gates by email (correct email for admin access).
