### ISSUE TITLE
"Example banner text area gb city"

### ISSUE THREAD

**Issue by harry-wood** [okfn/opendatacensus#622]
At the top of http://gb-city.census.okfn.org   I'm seeing a green box which looks like it should say something important but...   "Example banner text area gb city"   

Looks like it needs to be filled in  or removed.

**Comment by rgrp** [comment]
Good spot @harry-wood - this is because of the migration. Basically you set this in the config. Will correct now.

BTW: if you would like to act as a reviewer (checking submissions people have made) or admin (sorting config) for this UK local census and index let me know - we are looking for additional people right now!

**Comment by rgrp** [comment]
FIXED. (banner gone)
