### ISSUE TITLE
Accept new submission feature is not working

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#658]
@pwalsh , @vlevit - currently all submission are automatically accepted, and it doesn't matter if the value under approve_first_submission is true or false. Can you look and see what the problem is? And the global Index we want new submission NOT to be automatically accepted.

**Comment by vlevit** [comment]
The issue was in the global index spreadsheet. We have defined `approve_first_submission` settings two times: once one on the top and the second time near the bottom. The latest one was set to `TRUE` and it took precedence over the first one. That is why changing the first setting hasn't had any effect.

I removed `approve_first_submission` setting on the bottom and reloaded the config on the production. So now I believe it should work as expected.

**Comment by morchickit** [comment]
Great! Thank you! Closing this issue now.

**Comment by morchickit** [comment]
I saw another approve_first_submission ? I remover it as well.
