### ISSUE TITLE
Can't login to /admin

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#669]
Am getting an error today when trying to login to the /admin site. It redirects me to http://id.census.okfn.org/# and am getting this error
![screen shot 2015-08-25 at 10 28 40 am](https://cloud.githubusercontent.com/assets/595778/9474309/b4648386-4b14-11e5-951b-be4cfacfaa81.png)

**Comment by pwalsh** [comment]
Ok, what fun!

This is solved now.

The problem: we use in memory sessions (inadvisable, I know) and we rely on the session to store redirect info to get the user around from the id domains and back to where s/he was.

A few hours ago, we scaled up to 2 dynos, and this conflicts with the session state due to this storage being dyno-specific.

Obviously we want to be good 12 factor app/stateless server citizens, so I'll open a bug for that. Meanwhile the problem has been solved by changing from a horizontal to vertical scaling pattern (one big dyno instead of multiple small ones).

**Comment by ondrae** [comment]
Oh man, the exact same thing happened to me with my fork at
https://service-census.herokuapp.com/.

Right before our big event, where everyone was going to fill it out, I
thought I'd be smart and increase the number of dynos. Whoops.

Andrew Hyder
Developer Advocate :: 2013 Fellow
@hackyourcity <http://twitter.com/hackyourcity>

**Comment by pwalsh** [comment]
https://github.com/okfn/opendatacensus/issues/670

**Comment by pwalsh** [comment]
@ondrae yep, launch day blues :)
