### ISSUE TITLE
eventguide page

### ISSUE THREAD

**Issue by nealbastek** [okfn/opendatacensus#681]
@pwalsh can you do what you need to configure us a new content page at:

http://global.census.okfn.org/eventsguide/

Same set up as http://global.census.okfn.org/tutorial/

Thank you! @morchickit has content and will update that.

**Comment by pwalsh** [comment]
@nealbastek @morchickit 

Any page we add becomes part of the codebase and part of the configuration for every single census (local, regional), not only the global.

An "Events Guide" page seems quite specific, and not of general use as part of the codebase.

What is the user story for the new page? Why does it need to be part of the codebase itself, rather than, say, a thread on the forum?

**Comment by pwalsh** [comment]
(assigned to Mor as Neal is not yet assignable on this repo - sent invite to join)

**Comment by pwalsh** [comment]
@mor can we close this?
