### ISSUE TITLE
Translate the form to other languages 

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#726]
As a user, I want to use the index in my own language. For that, I need to have the form in my native language. 

@pwalsh - Was it possible in the past? 

@nealbastek  @tlacoyodefrijol  - FYI

**Comment by pwalsh** [comment]
@morchickit it is possible right now, and has been for years.

http://hr-city.census.okfn.org/submit/?place=zg&dataset=budget

http://census.okfn.org/site-admins/#localization

**Comment by tlacoyodefrijol** [comment]
@pwalsh it's not the form but the strings. We translated them in Transifex since last year but apparently the locale isn't working yet. https://www.transifex.com/okfn/open-data-census/viewstrings/#es_MX/messagespo-9/21897544

**Comment by pwalsh** [comment]
@tlacoyodefrijol it is the same thing. The code supports translations. In order to activate them on a particular site, two things need to happen:

* We add the extra strings to the codebase (I had not been alerted that additional translations are available, but you can see we have two languages in addition to English here: https://github.com/okfn/opendatacensus/tree/develop/census/locale)
* The site administrator updates her/his site settings to show the language selection options.
