### ISSUE TITLE
Can make form actions when texts are localised

### ISSUE THREAD

**Issue by tlacoyodefrijol** [okfn/opendatacensus#736]
So we're trying to fill the census for 2016 with the same information as the entries in 2015 but every time we submit, the app says "Submission marked as rejected". Is there a reason why this is happening?

**Comment by pwalsh** [comment]
@tlacoyodefrijol please provide some example URLs for data that is rejected.

**Comment by tlacoyodefrijol** [comment]
@pwalsh I figured it out. When the locale is set to Spanish. Once you hit publish, for some reason the app doesn't recognise that string and crashes. I set the locale to English and everything is working well now.

**Comment by pwalsh** [comment]
@morchickit wrote about this somewhere on the forum, but we don't have an issue opened here yet - it is a bug we'd like to fix. Mor, can you open an issue with everything you know about the locale preventing submissions?

**Comment by pwalsh** [comment]
I reopened and changed title of issue. This should be a very simple fix. The buttons from submission are all localised, and all use the actual value of the button as the hook for the submission action on the server. [Example](https://github.com/okfn/opendatacensus/blob/develop/census/views/create.html#L87). We need to change it so that the hook for handling forms on the server is a non-localised string from the button, and not the localised, use-facing value.

@borysyuk the link above is one of the actions, but from memory there is at least one more in the templates to check for.

**Comment by pwalsh** [comment]
DONE.
