### ISSUE TITLE
Submission screen shows "no entry" but there is an entry (just not in previous year)

### ISSUE THREAD

**Issue by rgrp** [okfn/opendatacensus#740]
Example 2016 submission for Bologna Business Listings: http://it-city.census.okfn.org/submission/a9f735ec-5a1a-46e1-9eb1-f98070610f0e

**Current shows "No Entry" everywhere* but here's 2014 and there is data: http://it-city.census.okfn.org/entry/bologna/business-listings/2014

Here's screenshot:

![image](https://cloud.githubusercontent.com/assets/180658/14942649/f6648126-0fba-11e6-842b-53531c49774b.png)

**Comment by pwalsh** [comment]
Hmm, this is a bit tricky based on changes to workflow last year (should entries from previous years be considered the "current entry" for new submission purposes). Not sure it is a bug or a feature. I'd say it is a bug, but we'll check with @morchickit for this year's work.

**Comment by morchickit** [comment]
This is connected to some issues we got from the US census. I will ask Danny about it and will ask in the forum. I think it's fine to keep it like this...

**Comment by morchickit** [comment]
and flagging this to @dannylammerhirt

**Comment by rgrp** [comment]
@morchickit i think this is something of a UX bug. I'd imagine seeing a diff against whatever was the entry - whenever that was. Especially an issue on local censuses where updates happen less often.

I can vouch for this having spent 30m+ trying to work out what was happening and debug this with some local group members.

**Comment by morchickit** [comment]
We need to work on the whole survey platform anyway since we didn't really touch it for two years. Let's wait until we know what we want to do it before we debug it...

**Comment by rgrp** [comment]
@morchickit ok - flagging that this *is* an issue right now for people wanting to do local censuses - e.g. OK Italia and OK England this weekend ...

**Comment by morchickit** [comment]
Cool, but the local census is not prioritise at the moment, so it will have to wait until we will work this for the Global index.

**Comment by rgrp** [comment]
@pwalsh @morchickit i actually now think is a bug and not just a feature. For example this submission for Nottingham in the UK has 2015 data and a submission from 2016 and yet it is showing "No Entry":

http://gb-city.census.okfn.org/submission/63e62cc4-0077-4f9a-bde2-e2c59bbc8784

@pwalsh any ideas on whether this is actually a bug or if somehow this is intended behaviour.

**Comment by pwalsh** [comment]
@rgrp i just don't remember what decisions where made on this last year. we are starting to warn up development for the 2016 census in the coming month, and we'll look at it then.

**Comment by pwalsh** [comment]
I've checked the examples (Bologna and Nottingham), read all the comments, and checked various supporting pages on the census for these datasets. 

All the read-only interfaces show correct info as far as I can see.

The issue is, as Rufus points out, when making a submission in a *new* year, and the latest entry is from a  *previous* year, the submission/review form does not pick up that *previous* entry and show it as the *current* entry.

I agree this is surprising behaviour for a user, and a bug.

@brew 

even though significant aspects of the submission/review will change, this year, I think this is a good bug to solve now, to:

- understand the flows in submission/review around this
- push to the godi-2015 branch before we make more comprehensive changes

**Comment by brew** [comment]
This issue is now fixed on staging (e.g. http://gb-city.next-census.okfn.org/submit/?place=nottingham&dataset=elections)
